services:
  - type: web
    name: consultancy-website
    env: docker
    plan: free
    branch: main
    dockerfilePath: ./Dockerfile
    healthCheckPath: /
    envVars:
      - key: APP_ENV
        value: production
      - key: APP_DEBUG
        value: false
      - key: APP_URL
        value: ${RENDER_EXTERNAL_URL}
      - key: APP_KEY
        value: base64:5GordeX6uczfMHpcGJ9Q+xygUkaLrZahdEYES0NX6sI=
      - key: DB_CONNECTION
        value: sqlite
      - key: DB_DATABASE
        value: /var/www/html/database/database.sqlite
